language: node_js

node_js: 8

jobs:
  include:

  - stage: install, check code style and coverage
    services:
    - mongodb
    env:
    - CXX=g++-4.8
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
      hosts:
      - localhost
    before_script:
    - npm install -g grunt-cli
    - sleep 10
    script:
    - grunt

  - stage: Publish to npm
    if: branch = master
    script:
    - echo "PUBLISH npm"
    deploy:
      provider: npm
      email: $NPM_EMAIL
      api_key: $NPM_TOKEN
      on:
        branch: master

  - stage: Publish to docker registry
    if: branch = master
    script:
    - echo "PUBLISH docker"
    - export PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -Fn '{ print $2 }' | sed 's/[n:",]//g' | tr -d '[[:space:]]')
    - export MAJOR_VERSION=$(echo ${PACKAGE_VERSION} | awk -F. '{ print $1 }')
    - echo Package version ${PACKAGE_VERSION}
    - echo Major version ${MAJOR_VERSION}
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - docker build -t deployer_go -f Dockerfile_go .
    - docker build -t deployer_node -f Dockerfile_node .
    - docker build -t deployer_nginx -f Dockerfile_nginx .

    - docker tag deployer_go:latest soajsorg/go:${PACKAGE_VERSION}
    - docker tag deployer_go:latest soajsorg/go:${MAJOR_VERSION}.x

    - docker tag deployer_node:latest soajsorg/node:${PACKAGE_VERSION}
    - docker tag deployer_node:latest soajsorg/node:${MAJOR_VERSION}.x

    - docker tag deployer_nginx:latest soajsorg/nginxTest:${PACKAGE_VERSION}
    - docker tag deployer_nginx:latest soajsorg/nginxTest:${MAJOR_VERSION}.x

    - docker images

    - docker push ${DOCKER_USERNAME}/go
    - docker push ${DOCKER_USERNAME}/node
    - docker push ${DOCKER_USERNAME}/nginxTest